### ISSUE TITLE
Building the documentation

### ISSUE THREAD

**Issue by hervebronnimann** [bloomberg/bde-tools#20]
I've asked john lakos before, but a huge part of the benefit of BDE-style libraries is their stellar documentation.  I write code and document the source in the same style, but I cannot produce the docs in the same style, because bde-tools doesn't expose the doxygen scripts / config files.  Is there any hope of getting those open-sourced?

**Comment by abeels** [comment]
Hi Herve.  We have been looking for quite a while now for an alternative to the scripts that produce our doxygen output, which is why we have been reluctant to publish them.  Among other issues, the scripts has been that they are hard to maintain, and depend on an out-of-date version of doxygen.  On the other hand, they do work.

Anyway, our search for an alternative has not produced anything usable yet, and we would like to help people produce documentation from BDE-style code, so we have finally decided to publish our existing scripts on an as-is basis.

I have assembled a candidate release, and we are conducting a final review.  I hope to be able to add the scripts to a `contrib` section of this repository in a week or so.

**Comment by hervebronnimann** [comment]
Hi:  sorry for coming back to the charge, you mentioned "about a week or so" a couple of weeks ago, I was wondering if there was any progress about this but you hadn't updated this issue tracker, or if you're still working on it.  Thanks!

**Comment by mversche** [comment]
@abeels has been pre-occupied with some teaching activities.  He should be back Monday - I've put a note in his calendar for when he gets back.

**Comment by mversche** [comment]
Looks like @abeels class goes through this week actually.  I've pinged him, but he likely won't look at this until next monday.

**Comment by abeels** [comment]
... or Tuesday, since Monday was a holiday.

We did a review of the candidate release, and there are now nothing blocking publication.  I will try to package it tomorrow.

**Comment by hervebronnimann** [comment]
That's wonderful news!

**Comment by hervebronnimann** [comment]
Any news about this?

**Comment by abeels** [comment]
Just pushed it.  Take a look at `contrib/bdedox`.
