### ISSUE TITLE
missing a release for 4.14.0.0?

### ISSUE THREAD

**Issue by chenrui333** [bloomberg/bde-tools#52]
👋 bde and bde-tools are used to be in sync, but looks like there is no release for 4.14.0.0, just curious if that is desired. Thanks!

relates to https://github.com/Homebrew/homebrew-core/pull/192100

**Comment by mversche** [comment]
We track issues with DRQS.  I've created DRQS 176799433 to track this.

**Comment by mversche** [comment]
FWIW, I believe the answer was that there were no changes to the bde-tools repository, so there is no bde-tools 4.14 label.

I.e., because our primary release platform is dpkg, and because of the build costs for promoting changes to dpkg, we only label and promote our repositories for a release when there are changes.

I'm not sure how Homebrew is picking the changes up.  In theory, we might label everything (all of our repos) for every release, but only promote the repositories in dpkg that have changed.  I'm not sure if that would address how Homebrew is updated.

**Comment by osubboo** [comment]
Nothing is missing. The BDE release is bumped only for the repos that participate in a release.
There were no changes for bde-tools, thus -> no version 4.14.0

**Comment by chenrui333** [comment]
got you, thanks!
